### ISSUE TITLE
bug: `Ask where to save the file each time` is broken

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#13]
When `Ask where to save the file each time` is unselected, it keeps saying "Couldn't find filepath of the selected file".

https://github.com/user-attachments/assets/2c9e6392-d297-4a42-a464-fe09240e20a3

**Comment by Vertuhai** [comment]
> When `Ask where to save the file each time` is unselected, it keeps saying "Couldn't find filepath of the selected file".
> 
>  Screen_Recording_20240807_163619_AntiSplit.M.mp4

What it is ?
I just tried to assemble the tweeter and everything is working correctly.
The only thing I did was re-sign him.

**Comment by Vertuhai** [comment]
I understand you, if you collect a package with this configuration, the file is not saved in the same directory as the APKS file itself.

> When `Ask where to save the file each time` is unselected, it keeps saying "Couldn't find filepath of the selected file".
> 
>  Screen_Recording_20240807_163619_AntiSplit.M.mp4

I understand you, if you collect a package with this configuration, the file is not saved in the same directory as the APKS file itself.

**Comment by Vertuhai** [comment]
I think the author will fix this).
Это не такая уж проблема .Файл сохраняется в папке по пути /storage/emulated/0/Android/data/com.abdurazaaqmohammed.AntiSplit/cache/ temp.apk 

Or you can turn on the second slider (Where to save).

**Comment by Kuddus73** [comment]
> Or you can turn on the second slider (Where to save).

Yh I know that,.
It just that this bug wasn't present in the past.

**Comment by AbdurazaaqMohammed** [comment]
Sorry I have fixed it in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Comment by Vertuhai** [comment]
> Sorry I have fixed it in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

The error has not been corrected))!
Here is a screenshot of the main screen of the program on how to compile.
![Screenshot_2024-08-07-18-34-53-094_com abdurazaaqmohammed AntiSplit-edit](https://github.com/user-attachments/assets/f77813a2-af8c-44e6-9461-a62183517638)

And I tried to compile these three files and all of them are equal (0).
![Screenshot_2024-08-07-18-35-18-983_bin mt plus-edit](https://github.com/user-attachments/assets/6883bbd3-404f-49c1-963f-a7d95dd6022a)

**Comment by Kuddus73** [comment]
> Sorry I have fixed it in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

@AbdurazaaqMohammed it's not fixed yet.
![Screenshot_20240807_184522_AntiSplit M](https://github.com/user-attachments/assets/2bd3e25c-80c8-4561-a98b-d8bd1b6a6a70)

**Comment by AbdurazaaqMohammed** [comment]
Sorry it was working on my end

I tried to fix it again please check the latest release https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6

**Comment by Vertuhai** [comment]
> Sorry it was working on my end
> 
> I tried to fix it again please check the latest release https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6

You did great, you finally fixed it.
And with the signature (v1-v2 - v3) everything is also good, now they will write less about the fact that the error is Android 14.
